<?php

namespace Database\Factories;

use App\Models\CostSnapshot;
use App\Models\Currency;
use Illuminate\Database\Eloquent\Factories\Factory;

class CostSnapshotFactory extends Factory
{
    protected $model = CostSnapshot::class;

    public function definition(): array
    {
        return [
            'entity_type' => fake()->randomElement(['ITEM','PREPARED','RECIPE']),
            'entity_id' => fake()->numberBetween(1, 1000),
            'as_of_date' => fake()->dateTimeBetween('-1 month', 'now'),
            'method' => fake()->randomElement(['LAST','MOVING_AVG','FIFO','STANDARD']),
            'unit_cost' => fake()->randomFloat(3, 0.1, 500),
            'currency_id' => Currency::factory(),
            'details' => ['note' => 'snapshot generated by factory'],
        ];
    }
}
